refactor: optimization attempts - group steps that must run before the build and cache build dir. Clean up file

diff --git a/.github/workflows/build-ios-demos.yml b/.github/workflows/build-ios-demos.yml
--- a/.github/workflows/build-ios-demos.yml
+++ b/.github/workflows/build-ios-demos.yml
@@ -33,7 +33,7 @@ jobs:
   build:
     needs: generate-matrix
     runs-on: macos-latest
-    timeout-minutes: 60
+    timeout-minutes: 15
     strategy:
       matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
       max-parallel: 3
@@ -42,7 +42,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          sparse-checkout: demos/ios
+          sparse-checkout: ${{ matrix.demo }}
 
       - name: Clone MASTestApp-iOS repository
         uses: actions/checkout@v4
@@ -53,30 +53,34 @@ jobs:
       - name: Install dependencies
         run: brew install ldid
 
-      - name: Replace files and prepare build
+      - name: Set default scheme and iOS deployment target
         run: |
-          demo="${{ matrix.demo }}"
-          if [ ! -d "$demo" ]; then
-            echo "Demo directory not found: $demo"
-            exit 1
-          fi
-
-          echo "Processing $demo"
-          [ -f "$demo/MastgTest.swift" ] && cp -f "$demo/MastgTest.swift" MASTestApp-iOS/MASTestApp/MastgTest.swift && echo "Copied MastgTest.swift for $demo" || echo "No MastgTest.swift found for $demo"
-          [ -f "$demo/Info.plist" ] && cp -f "$demo/Info.plist" MASTestApp-iOS/MASTestApp/Info.plist && echo "Copied Info.plist for $demo" || echo "No Info.plist found for $demo"
+          cd MASTestApp-iOS
+          default=$(xcodebuild -list -json | jq -r '.project.targets[0]')
+          echo "DEFAULT_SCHEME=$default" >> "$GITHUB_ENV"
+          echo "Using default scheme: $default"
 
           DEPLOYMENT_TARGET=14.4
           echo "Setting iOS Deployment Target to $DEPLOYMENT_TARGET"
           sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = $DEPLOYMENT_TARGET;/g" "MASTestApp-iOS/MASTestApp.xcodeproj/project.pbxproj"
 
+      - name: Cache build directory
+        uses: actions/cache@v4
+        with:
+          path: build/
+          key: ios-demos-${{ hashFiles('MASTestApp-iOS/MASTestApp.xcodeproj/project.pbxproj') }}
 
-      - name: Set Default Scheme
+      - name: Replace files with demo and prepare build
         run: |
-          cd MASTestApp-iOS
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo "DEFAULT_SCHEME=$default" >> "$GITHUB_ENV"
-          echo "Using default scheme: $default"
+          demo="${{ matrix.demo }}"
+          [ -d "$demo" ] || (
+            echo "Demo directory not found: $demo"
+            exit 1
+          )
+
+          echo "Processing $demo"
+          [ -f "$demo/MastgTest.swift" ] && cp -f "$demo/MastgTest.swift" MASTestApp-iOS/MASTestApp/MastgTest.swift && echo "Copied MastgTest.swift for $demo" || echo "No MastgTest.swift found for $demo"
+          [ -f "$demo/Info.plist" ] && cp -f "$demo/Info.plist" MASTestApp-iOS/MASTestApp/Info.plist && echo "Copied Info.plist for $demo" || echo "No Info.plist found for $demo"
 
       - name: Build the app (unsigned)
         run: |
@@ -90,7 +94,7 @@ jobs:
             CODE_SIGNING_REQUIRED=NO \
             CODE_SIGNING_ALLOWED=NO
 
-      - name: Add Entitlements
+      - name: Pseudo sign with entitlements.plist
         run: |
           ldid -SMASTestApp-iOS/entitlements.plist "$GITHUB_WORKSPACE/build/MASTestApp.xcarchive/Products/Applications/MASTestApp.app/MASTestApp"
 
@@ -108,12 +112,6 @@ jobs:
         run: |
           echo "Listing generated IPA in output directory:"
           ls -l output/
-
-      - name: List all files in repository
-        run: |
-          find . -type f
-          echo exists jq?
-          jq --version || echo "jq not found"
 
       - name: Upload IPA
         uses: actions/upload-artifact@v4
